import Head from 'next/head'
import css from './index.module.css'

import { useRouter } from 'next/router'
import Image from 'next/image'
import Hand from './public/Hand.png';
import Face from './public/face.png';
import { use } from 'react'
import NavBar from './component/NavBar'

export default function Google() {
  const router = useRouter();
  return (<>
    <Head>
        <title>blrow.world</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={css.main}>
      <NavBar/>
      <div className={css.faceContainer} >
        <ZeFace zIndex={9} mixBlendMode={'screen'} opacity={'50%'}/>
        <ZeFace zIndex={2} mixBlendMode={'hard-light'} opacity={'20%'}/>
      </div>
      <div className={css.headingContainer}>
        <div className={css.titleContainer}>
          <div>
            THE EXHIBITION
          </div>
        </div>
        <div className={css.subTitleContainer}>
          <div>
            Artist #0000001
          </div>
          <div>
            begins in <span style={{color: 'greenyellow'}}>30:00</span>
          </div>
        </div>

      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size1}
        >
          <Image
            src={Hand}
            style={{
              // objectFit: 'contain',
              // position: 'absolute',
              width: '100%',
              height: 'auto'
            }}
          />
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size2}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size2}
        >
          <ZeHand/>
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
      </div>
    </main>
  </>)
}

export async function getStaticProps(context) {

  return {
    props: {}, // will be passed to the page component as props
  }
}

function ZeHand(){
  return( 
    <Image
    src={Hand}
    style={{
      // objectFit: 'contain',
      // position: 'absolute',
      width: '100%',
      height: 'auto'
    }}
  />
  )
}

function ZeFace({zIndex, mixBlendMode, opacity}){
  return(
    <div
      style={{
        opacity: opacity,
        zIndex: zIndex,
        width: '100vw',
        mixBlendMode: mixBlendMode, //hard-light, screen
        position: 'fixed', //'absolute'
        right: '0',
        display: 'flex',
        flexDirection: 'row-reverse',
      }}
    >
      <Image
        src={Face}
        style={{
          width: '69%',
          height: 'auto',
          objectFit: 'contain'
        }}
      />
    </div>
  )
}