import Head from 'next/head'
import css from './index.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Image from 'next/image'
import GogglesIcon from './GogglesIcon.png';
import Hand from './Hand.png';
import { use } from 'react'

export default function Google() {
  const router = useRouter();
  return (<>
    <Head>
        <title>blrow.world</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={css.main}>
      <div
        className={css.navBarContainer}
      >
        <div
          style={{
            height: '30px',
            width: '60px',
            position: 'relative'
          }}
          onClick={()=>{
            router.push('/google');
          }}
        >
          <Image
            src={GogglesIcon}
            fill
          />
        </div>
      </div>

      <div
        className={css.headingContainer}
      ></div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size1}
        >
          <Image
            src={Hand}
            style={{
              // objectFit: 'contain',
              // position: 'absolute',
              width: '100%',
              height: 'auto'
            }}
          />
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size2}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size2}
        >
          <ZeHand/>
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size3}
        >
          <ZeHand/>
        </div>
      </div>

      <div
        className={css.paintingSetContainer}
      >
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
        <div
          className={css.paintingContainer + ' ' + css.size4}
        >
          <ZeHand/>
        </div>
      </div>
    </main>
  </>)
}

export async function getStaticProps(context) {

  return {
    props: {}, // will be passed to the page component as props
  }
}

function ZeHand(){
  return( 
    <Image
    src={Hand}
    style={{
      // objectFit: 'contain',
      // position: 'absolute',
      width: '100%',
      height: 'auto'
    }}
  />
  )
}